### ISSUE TITLE
Blocked e-mails from siraj-lighting.com

### ISSUE THREAD

**Issue by CyberCr33p** [mxroute/rspamd_rules#25]
Hello,

Today a customer contact me and told me that he can't get e-mails from @siraj-lighting.com

Τhe sender envelope shows SRS0=10TokQ=XX=siraj-lighting.com=Logistics@yourhostingaccount.com so I guess all mailboxes that use powweb as the mail provider have envelope @yourhostingaccount.com and are blocked.

Can you please check if you get much spam from yourhostingaccount.com and if not to unblock it?

Thank you in advance.

**Comment by mxroute** [comment]
I see a lot of spam coming in from @yourhostingaccount.com. Do you have any insight on what this is? I'll explain what I see and see if you or anyone else can shed more light on it:

The senders, as you noted this one being SRS0=10TokQ=XX=siraj-lighting.com=Logistics@yourhostingaccount.com, all seem to suggest something other than what is happening. That sender right there, for example, suggests that you own yourhostingaccount.com and you are forwarding email which is delivered to it, to another email account elsewhere. Because it's rewriting the sender with an SRS envelope sender, so the final @ domain at the end of that should be yours.

But I know you don't own yourhostingaccount.com. I know none of my customers own yourhostingaccount.com. Yet, they are acting as an email forwarder to a bunch of my customers. I do not know why. If you receive email from siraj-lighting.com, it should be coming from siraj-lighting.com, not from yourhostingaccount.com with an SRS forwarder unless you own yourhostingaccount.com.

So what exactly is happening here, what is yourhostingaccount.com and why is it acting in this way?

**Comment by CyberCr33p** [comment]
Hello Jarland and thank you for your reply.

powweb.com uses yourhostingaccount.com for their servers. It's an old (since 1999) and big provider with many customers so I would expect a lot of e-mails sent from their servers.

Someone sends e-mail from logistics@siraj-lighting.com to an e-mail that I host (let's say it's info@example.com).

The envelope of the incoming e-mails shows SRS0=10TokQ=XX=siraj-lighting.com=Logistics@yourhostingaccount.com . I don't know why they do SRS and use their domain instead of siraj-lighting.com , maybe they want to avoid issues with SPF if siraj-lighting.com doesn't have the correct SPF record?

Of course it's bad practice what they do, but I believe a lot of legitimate e-mail is blocked if you don't remove yourhostingaccount.com from your list.

**Comment by mxroute** [comment]
I'm afraid I only see spam in the logs, and currently within the last hour, from @yourhostingaccount.com. Presently I believe that this filter is accomplishing what I set out to.
